version: '3'
services:
 odind:
  image: odinblockchain/odind-docker
  container_name: odind-docker
  restart: always
  volumes:
   - ~/odin-wallet/:/root/.odin/
  ports:
  - 22100:22101
  command: odind -server -rest -rpcallowip=0.0.0.0/0 -rpcuser=node -rpcpassword=internal
 node:
  build:
   context: ./
   dockerfile: node.docker
  links:
  - odind
  container_name: node
  ports: 
  - 80
